M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date dom 07 may 2023 16:17:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-07T16:17:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X9.0Y-9.0
X9.0Y-75.0
X101.0Y-9.0
X101.0Y-75.0
T2
X82.37Y-68.37
T0
M30
