M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date dom 07 may 2023 16:07:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-07T16:07:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X99.0Y-67.0
X99.0Y-133.0
X191.0Y-67.0
X191.0Y-133.0
T2
X172.37Y-126.37
T0
M30
